### ISSUE TITLE
[NEW]: Add automation to create branch from new issues

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/dotfiles#311]
**Configuration for:**
GitHub

**Files required:**
Add an automation to create a new branch for each issue that is created:

```yaml
on:
  issues:
    types: [opened]
```
