### ISSUE TITLE
[BUG]: Startpage CSS is out of date

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/dotfiles#374]
**Describe the bug**
`.local/share/suckless/surf/styles/startpage.com.css` is now longer up to date with the latest version of startpage.com.

**To Reproduce**

1. Search for *foo* on startpage
2. See ads

**Expected behavior**
No ads

**Additional context**
```css
.mainline-results #gcsa-top {
    display: none;
}
```
